In [1]:
import numpy as np
import pandas as pd

In [4]:
date=pd.read_csv('orders.csv')
time =pd.read_csv('messages.csv')

In [5]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [6]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

### since date in python by default is an Object and we have to convert it to date and time manually

## Working with Dates

In [8]:
date['date']= pd.to_datetime(date['date'])

In [10]:
date.info() # now date time is in date-time datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## Extract Year

In [12]:
year= date['date_year'] = date['date'].dt.year
year

0      2019
1      2018
2      2018
3      2019
4      2019
       ...
995    2018
996    2018
997    2019
998    2019
999    2019
Name: date, Length: 1000, dtype: int32

## Extract Month

In [14]:
month= date['date_year'] = date['date'].dt.month
month

0      12
1       8
2      10
3       8
4       1
       ..
995    10
996    12
997     5
998     3
999    10
Name: date, Length: 1000, dtype: int32

In [16]:
month_name= date['date_year'] = date['date'].dt.month_name()
month_name

0      December
1        August
2       October
3        August
4       January
         ...
995     October
996    December
997         May
998       March
999     October
Name: date, Length: 1000, dtype: object

In [ ]:
month_name= date['date_year'] = date['date'].dt.month_name()
month_name

## Extract days

In [20]:
day=date['date_day']= date['date'].dt.day  #which day of the month
day

0      10
1      15
2      23
3      17
4       6
       ..
995     8
996     6
997     7
998     3
999    15
Name: date, Length: 1000, dtype: int32

In [21]:
day=date['date_day']= date['date'].dt.dayofweek
day

0      1
1      2
2      1
3      5
4      6
      ..
995    0
996    3
997    1
998    6
999    1
Name: date, Length: 1000, dtype: int32

In [22]:
day=date['date_day']= date['date'].dt.day_name()
day

0        Tuesday
1      Wednesday
2        Tuesday
3       Saturday
4         Sunday
         ...
995       Monday
996     Thursday
997      Tuesday
998       Sunday
999      Tuesday
Name: date, Length: 1000, dtype: object

In [25]:
date.drop(columns=['product_id','city_id','orders']).head()

        date date_year   date_day
0 2019-12-10  December    Tuesday
1 2018-08-15    August  Wednesday
2 2018-10-23   October    Tuesday
3 2019-08-17    August   Saturday
4 2019-01-06   January     Sunday

## Is it weekend?

In [28]:
date['date_is_weekend']= np.where(date['date_day'].isin(['Sunday','Saturday']),1,0)

date.drop(columns=['product_id','city_id','orders']).head()

        date date_year   date_day  date_is_weekend
0 2019-12-10  December    Tuesday                0
1 2018-08-15    August  Wednesday                0
2 2018-10-23   October    Tuesday                0
3 2019-08-17    August   Saturday                1
4 2019-01-06   January     Sunday                1

## Extract week of the Year

In [34]:
date['date_week']=date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

        date date_year   date_day  date_is_weekend  quarter  date_week
0 2019-12-10  December    Tuesday                0        4         50
1 2018-08-15    August  Wednesday                0        3         33
2 2018-10-23   October    Tuesday                0        4         43
3 2019-08-17    August   Saturday                1        3         33
4 2019-01-06   January     Sunday                1        1          1

## Exatract Semester

In [36]:
date['semester']= np.where(date['quarter'].isin([1,2]),1,2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_day,date_is_weekend,quarter,date_week,semester
0,2019-12-10,December,Tuesday,0,4,50,2
1,2018-08-15,August,Wednesday,0,3,33,2
2,2018-10-23,October,Tuesday,0,4,43,2
3,2019-08-17,August,Saturday,1,3,33,2
4,2019-01-06,January,Sunday,1,1,1,1

## Time elapsed between dates

In [38]:
import datetime
today= datetime.datetime.today()
today

datetime.datetime(2026, 7, 18, 12, 31, 25, 891336)

In [39]:
today - date['date']

0     2412 days 12:31:25.891336
1     2894 days 12:31:25.891336
2     2825 days 12:31:25.891336
3     2527 days 12:31:25.891336
4     2750 days 12:31:25.891336
                 ...
995   2840 days 12:31:25.891336
996   2781 days 12:31:25.891336
997   2629 days 12:31:25.891336
998   2694 days 12:31:25.891336
999   2468 days 12:31:25.891336
Name: date, Length: 1000, dtype: timedelta64[ns]

In [40]:
(today-date['date']).dt.days

0      2412
1      2894
2      2825
3      2527
4      2750
       ...
995    2840
996    2781
997    2629
998    2694
999    2468
Name: date, Length: 1000, dtype: int64

In [43]:
# months passed
np.round((today - date['date']).dt.days / 30.44, 0)

0      79.0
1      95.0
2      93.0
3      83.0
4      90.0
       ...
995    93.0
996    91.0
997    86.0
998    89.0
999    81.0
Name: date, Length: 1000, dtype: float64

## WOrking with time:

In [44]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [45]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [46]:
time['date']= pd.to_datetime(time['date'])

In [47]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [48]:
time['hour']=time['date'].dt.hour
time['min']=time['date'].dt.minute
time['sec']=time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

##Time Difference

In [49]:
today - time['date']

0     4598 days 11:41:25.891336
1     4462 days 12:51:25.891336
2     4948 days 12:10:25.891336
3     4250 days 12:00:25.891336
4     4647 days 13:20:25.891336
                 ...
995   5237 days 11:41:25.891336
996   4558 days 13:17:25.891336
997   5023 days 12:54:25.891336
998   5139 days 12:57:25.891336
999   4411 days 13:06:25.891336
Name: date, Length: 1000, dtype: timedelta64[ns]

## time in secs

In [50]:
(today-time['date'])/np.timedelta64(1,'s')

0      3.973093e+08
1      3.855631e+08
2      4.275510e+08
3      3.672432e+08
4      4.015488e+08
           ...
995    4.525189e+08
996    3.938590e+08
997    4.340337e+08
998    4.440562e+08
999    3.811576e+08
Name: date, Length: 1000, dtype: float64

## time in hrs

In [51]:
(today-time['date'])/np.timedelta64(1,'h')

0      110363.690525
1      107100.857192
2      118764.173859
3      102012.007192
4      111541.340525
           ...
995    125699.690525
996    109405.290525
997    120564.907192
998    123348.957192
999    105877.107192
Name: date, Length: 1000, dtype: float64