In [ ]:
df=pd.read_csv("/content/placement data.csv")

In [ ]:
import pandas as pd

## Opening a local CSV file

In [ ]:
df.head()

   cgpa   iq  placement
0   6.8  123          1
1   5.9  106          0
2   5.3  121          0
3   7.4  132          1
4   5.8  142          0

In [ ]:
df.iloc[:,1:]

     iq  placement
0   123          1
1   106          0
2   121          0
3   132          1
4   142          0
..  ...        ...
95  200          0
96   42          0
97  182          1
98  103          1
99  113          1

[100 rows x 2 columns]

## Opening a CSV file from URL

In [ ]:
import requests
from io import StringIO
url="https://drive.google.com/uc?id=13a2WyLoGxQKXbN_AIjrOogIlQKNe9uPm&export=download"
headers={"User-Agent":"Mozilla/5.0 (Macitosh;Intel Mac OS X; rv:66.0)Gecko/20100101 Firefox/66.0"}
req=requests.get(url,headers=headers)
data=StringIO(req.text)
pd.read_csv(data)

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,1,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,Plastics,3498
1,2,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2015,Glass / Ceramics / Concrete,4952
2,3,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287
3,4,2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921
4,5,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870
...,...,...,...,...,...,...,...,...,...
95,96,0a0bfFbBbB8eC7c,Holmes Group,https://mcdowell.org/,Ethiopia,Right-sized zero tolerance focus group,1975,Photography,2988
96,97,BA6Cd9Dae2Efd62,Good Ltd,http://duffy.com/,Anguilla,Reverse-engineered composite moratorium,1971,Consumer Services,4292
97,98,E7df80C60Abd7f9,Clements-Espinoza,http://www.flowers.net/,Falkland Islands (Malvinas),Progressive modular hub,1991,Broadcast Media,236
98,99,AFc285dbE2fEd24,Mendez Inc,https://www.burke.net/,Kyrgyz Republic,User-friendly exuding migration,1993,Education Management,339
99,100,e9eB5A60Cef8354,Watkins-Kaiser,http://www.herring.com/,Togo,Synergistic background access,2009,Financial Services,2785

## Sep Parameter (by default-"comma,-")

####if we pass a tsv file in place of csv files then it wont be ble to read the  data from that tsv file


---

In [ ]:
pd.read_csv("brasillian.tsv",sep="\t")   #this wont read tsv files

### names paramter of read_csv()

In [ ]:
pd.read_csv('brasillian.tsv',sep='\t',names=['sno','name','relese_year','rating','votes'])

since the first row becomes the column names sometimes we just need to add another paraamter of the `read_csv()` which is `names` -> all the values passed to names parameter becomes the attributes names!

Index-Col parameter

In [ ]:
pd.read_csv('/content/placement data.csv',index_col='cgpa')
#this will remove the index column and make enrolle_id as the index (0,1,2,3,4,5,6,7,8,9...)

       iq  placement
cgpa
6.8   123          1
5.9   106          0
5.3   121          0
7.4   132          1
5.8   142          0
...   ...        ...
4.3   200          0
4.4    42          0
6.7   182          1
6.3   103          1
6.2   113          1

[100 rows x 2 columns]

### Header Parameter->
###### used when the attributes becomes the first row and we want them to be the attributes name

In [ ]:
pd.read_csv('/content/placement data.csv',header=1)  # the first row will become the attribute name

    6.8  123  1
0   5.9  106  0
1   5.3  121  0
2   7.4  132  1
3   5.8  142  0
4   7.1   48  1
..  ...  ... ..
94  4.3  200  0
95  4.4   42  0
96  6.7  182  1
97  6.3  103  1
98  6.2  113  1

[99 rows x 3 columns]

### Use-cols parameter

-> this is used to gather and select only those columns which are needed in upcoming processes.
selecting main columns

In [ ]:
pd.read_csv('/content/placement data.csv',usecols=['placement','iq'])

     iq  placement
0   123          1
1   106          0
2   121          0
3   132          1
4   142          0
..  ...        ...
95  200          0
96   42          0
97  182          1
98  103          1
99  113          1

[100 rows x 2 columns]

###  Squeeze Parameters

-> dpereceated pandas command

In [ ]:
pd.read_csv('/content/placement data.csv',usecols=['placement','iq'],squeeze=True) #this wont run
#because squeeze is a deprecated command

### Skiprows-> determines the number of rows we want to skip.

<p style="color:red"> we can even write a python function through which we can determine which rows we have to skip
eg: lambda x:x in [0,5]
</p>

In [ ]:
pd.read_csv('/content/placement data.csv',skiprows=[0,1])
#it is not necessary to remove/skip consecutive rows we can actually remove
#any row number we will mention!!

    5.9  106  0
0   5.3  121  0
1   7.4  132  1
2   5.8  142  0
3   7.1   48  1
4   5.7  143  0
..  ...  ... ..
93  4.3  200  0
94  4.4   42  0
95  6.7  182  1
96  6.3  103  1
97  6.2  113  1

[98 rows x 3 columns]

### nrows -> it is a parameter through which we can select the number of rows we want in our dataframe

In [ ]:
pd.read_csv('/content/placement data.csv',nrows=5)

   cgpa   iq  placement
0   6.8  123          1
1   5.9  106          0
2   5.3  121          0
3   7.4  132          1
4   5.8  142          0

### Encoding Parameter
the encoding of our datasets should be `UTF-8`

sometimes it is not `UTF-8`
then we need to convert it to `UTF-8`

In [ ]:
pd.read_csv('/content/archive.zip',encoding="latin-1")

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51712,https://www.zomato.com/bangalore/best-brews-fo...,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,080 40301477,Whitefield,Bar,NaN,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51713,https://www.zomato.com/bangalore/vinod-bar-and...,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,+91 8197675843,Whitefield,Bar,NaN,Finger Food,600,[],[],Pubs and bars,Whitefield
51714,https://www.zomato.com/bangalore/plunge-sherat...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000",[],[],Pubs and bars,Whitefield
51715,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,https://www.zomato.com/bangalore/the-nest-the-...,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

### Encoding bad Lines
if there are few rows which are not upto the mark we need to fix them ->( if there are higehr number of row values as compared to that of needed number of values)

-> used when there is parser error!!

In [ ]:
pd.read_csv('/content/archive.zip',error_bad_lines=False)

### Dtypes Parameter

if any column is taking float values and it can easily work with int data then we can convert it to int as well.

In [ ]:
pd.read_csv('/content/placement data.csv',dtype={'placement':float}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   cgpa       95 non-null     float64
 1   iq         100 non-null    int64
 2   placement  100 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

### Handling dates
in general if we dont apply date parser then dates are treated as string and we cant use functionality of dates i.e filtering data on the basis of dates that's why we use a date parser.

In [ ]:
pd.read_csv('/content/placement data.csv',parse_dates=['iq']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   cgpa       95 non-null     float64
 1   iq         100 non-null    object
 2   placement  100 non-null    int64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.5+ KB

/tmp/ipykernel_8450/1875254321.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv('/content/placement data.csv',parse_dates=['iq']).info()

### Convertors->
we want to give shory names to our data values

In [ ]:
def rename(iq):
  if iq>='100':
    return "genius"
  else:
    return name

In [ ]:
pd.read_csv('/content/placement data.csv',converters={'iq':rename})

    cgpa      iq  placement
0    6.8  genius          1
1    5.9  genius          0
2    5.3  genius          0
3    7.4  genius          1
4    5.8  genius          0
..   ...     ...        ...
95   4.3  genius          0
96   4.4  genius          0
97   6.7  genius          1
98   6.3  genius          1
99   6.2  genius          1

[100 rows x 3 columns]

### Na_Values Parameters
-> nan values= missing values
-> there are various methods like fillna() dropna() for such values but in various datasets there are hyphen values (-) instead of nan values for that we use this method!

In [ ]:
pd.read_csv('/content/placement data.csv',na_values=["1"])

    cgpa   iq  placement
0    6.8  123        NaN
1    5.9  106        0.0
2    5.3  121        0.0
3    7.4  132        NaN
4    5.8  142        0.0
..   ...  ...        ...
95   4.3  200        0.0
96   4.4   42        0.0
97   6.7  182        NaN
98   6.3  103        NaN
99   6.2  113        NaN

[100 rows x 3 columns]

### Loading a HUGE dataset in CHUNKS.:
-> if the dataset size is huge then we can load it in chunks by using a parameter i.e. chunksize

In [ ]:
df=pd.read_csv('/content/placement data.csv',chunksize=50)   #100 rows

In [ ]:
df

In [ ]:
for chunks in df:
  print(chunks.shape)  #divided into 2

(50, 3)
(50, 3)